### ISSUE TITLE
Only the content for page 1 is shown

### ISSUE THREAD

**Issue by DylanFPS** [DMP9Labs/ClickToWebsite#5]
### What's the problem?

No content shows if there is more than one page on Materialize **and** page 1 is called `1` and page 2 is called `2`

### What's happening?

If it makes a difference, i did include a logo.

### How do we recreate the problem?

Title: 1
Description: 1
Page Amount: 2
Page 1 Name: 1
Page 2 Name: 2
Page 1 Paragraph Title: title1
Page 1 Paragraph Content: content1
Page 2 Paragraph Title: title2
Page 2 Paragraph Content: content2

### Anything else you need to tell us?

I uploaded the output to http://car-park-attendant-robert-88384.bitballoon.com/

**Comment by AzyIsCool** [comment]
Fixed
